package konstructs.api;

import java.io.Serializable;
import java.util.Arrays;

/**
 * BlockType is a class that holds all relevant information regarding
 * a block's type. Instances of this class is generated when the
 * server is started from the server configuration. It is immutable
 * and serializable.
 */
public final class BlockType implements Serializable {
    public static final String SHAPE_BLOCK = BlockShape.BLOCK.getShape();
    public static final String SHAPE_PLANT = BlockShape.PLANT.getShape();

    public static final String STATE_SOLID = BlockState.SOLID.getState();
    public static final String STATE_LIQUID = BlockState.LIQUID.getState();
    public static final String STATE_GAS = BlockState.GAS.getState();
    public static final String STATE_PLASMA = BlockState.PLASMA.getState();

    private final int[] faces;
    private final BlockShape blockShape;
    private final boolean obstacle;
    private final boolean transparent;
    private final BlockState blockState;

    /**
     * Constructs an immutable BlockType.
     * @param faces the texture index for all faces of a BlockType
     * @param shape the shape of the block
     * @param obstacle is this BlockType an obstacle?
     * @param transparent is this BlockType transparent?
     * @deprecated As of API version 0.1.3 (will be removed in 0.2.+)
     *             Replaced by {@link #BlockType(int[], String, boolean, boolean, String)}.
     *             This constructor always sets state to {@link #STATE_SOLID}
     * @see #getFaces()
     * @see #getShape()
     * @see #isObstacle()
     * @see #isTransparent()
     */
    @Deprecated
    public BlockType(int[] faces, String shape, boolean obstacle, boolean transparent) {
        this(faces, BlockShape.fromString(shape), obstacle,transparent, BlockState.SOLID);
    }

    /**
     * Constructs an immutable BlockType.
     * @param faces the texture index for all faces of a BlockType
     * @param shape the shape of the block
     * @param obstacle is this BlockType an obstacle?
     * @param transparent is this BlockType transparent?
     * @param state the state of the block
     * @deprecated As of API 0.1.7 (will be removed in 0.2.+)
     *             Replaced by {@link #BlockType(int[], BlockShape, boolean, boolean, BlockState)}
     * @see #getFaces()
     * @see #getShape()
     * @see #isObstacle()
     * @see #isTransparent()
     * @see #getState()
     */
    @Deprecated
    public BlockType(int[] faces, String shape, boolean obstacle, boolean transparent, String state) {
        this(faces, BlockShape.fromString(shape), obstacle, transparent, BlockState.fromString(state));
    }

    public BlockType(int[] faces, BlockShape shape, boolean obstacle, boolean transparent, BlockState state) {
        this.faces = faces;
        this.blockShape = shape;
        this.obstacle = obstacle;
        this.transparent = transparent;
        this.blockState = state;
    }

    /**
     * Returns the texture indexes for this block type. A texture index
     * is an index generated by the server for the position at which
     * the texture for each of the block's faces is stored.
     * @return the array containing the texture indexes for this block type
     */
    public int[] getFaces() {
        return faces;
    }

    /**
     * Returns the shape of this block type. The shape of the block can
     * currently only be either of <code>BlockType.SHAPE_BLOCK</code> or
     * <code>BlockType.SHAPE_PLANT</code>.
     * @deprecated As of API 0.1.7 (will be removed in 0.2.+). Use {@link #getBlockShape()} instead.
     * @return the shape of the block
     */
    @Deprecated
    public String getShape() {
        return blockShape.getShape();
    }

    /**
     * Returns the shape of this block type.
     * @return the shape of the block
     */
    public BlockShape getBlockShape() {
        return blockShape;
    }

    /**
     * Checks if this block type is seen as an obstacle or not. A block with
     * an obstacle type can not be passed through by the player.
     * @return true if this block is an obstacle, otherwise false
     */
    public boolean isObstacle() {
        return obstacle;
    }

    /**
     * Checks if this block type is seen as transparent by the player.
     * @return true if this block is transparent otherwise false
     */
    public boolean isTransparent() {
        return transparent;
    }

    /**
     * Returns the state of this block type. The state of the block
     * can currently be {@link #STATE_SOLID}, {@link #STATE_LIQUID},
     * {@link #STATE_GAS}, {@link #STATE_PLASMA}
     * @deprecated As of API 0.1.7 (will be removed in 0.2.+). Use {@link #getBlockState()} instead.
     * @return the state of this block type
     */
    @Deprecated
    public String getState() {
        return blockState.getState();
    }

    /**
     * Returns the state of this block type.
     * @return the state of this block type
     */
    public BlockState getBlockState() {
        return blockState;
    }

    /**
     * Returns a copy with a new value for the faces
     * field.
     * @param faces the new value for faces
     * @return the copy
     * @see #getFaces()
     */
    public BlockType withFaces(int[] faces) {
        return new BlockType(faces, blockShape, obstacle, transparent, blockState);
    }

    /**
     * Returns a copy with a new value for the shape
     * field.
     * @param shape the new value for shape
     * @deprecated As of 0.1.7 (will be removed in 0.2.+). Use {@link #withBlockShape(BlockShape)} instead.
     * @return the copy
     * @see #getShape()
     */
    @Deprecated
    public BlockType withShape(String shape) {
        return new BlockType(faces, BlockShape.fromString(shape), obstacle, transparent, blockState);
    }

    /**
     * Returns a copy with a new value for the shape
     * field.
     * @param shape the new value for shape
     * @return the copy
     * @see #getBlockShape()
     */
    public BlockType withBlockShape(BlockShape shape) {
        return new BlockType(faces, shape, obstacle, transparent, blockState);
    }

    /**
     * Returns a copy with a new value for the obstacle
     * field.
     * @param obstacle the new value for obstacle
     * @return the copy
     * @see #isObstacle()
     */
    public BlockType withObstacle(boolean obstacle) {
        return new BlockType(faces, blockShape, obstacle, transparent, blockState);
    }

    /**
     * Returns a copy with a new value for the transparent
     * field.
     * @param transparent the new value for transparent
     * @return the copy
     * @see #isTransparent()
     */
    public BlockType withTransparent(boolean transparent) {
        return new BlockType(faces, blockShape, obstacle, transparent, blockState);
    }

    /**
     * Returns a copy with a new value for the state
     * field.
     * @param state the new value for state
     * @deprecated As of 0.1.7 (will be removed in 0.2.+). Use {@link #withBlockState(BlockState)} instead.
     * @return the copy
     * @see #getState()
     */
    @Deprecated
    public BlockType withState(String state) {
        return new BlockType(faces, blockShape, obstacle, transparent, BlockState.fromString(state));
    }

    /**
     * Returns a copy with a new value for the state
     * field.
     * @param state the new value for state
     * @return the copy
     * @see #getBlockState()
     */
    public BlockType withBlockState(BlockState state) {
        return new BlockType(faces, blockShape, obstacle, transparent, state);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        BlockType blockType = (BlockType) o;

        if (obstacle != blockType.obstacle) return false;
        if (transparent != blockType.transparent) return false;
        if (!Arrays.equals(faces, blockType.faces)) return false;
        if (!blockShape.equals(blockType.blockShape)) return false;
        return blockState.equals(blockType.blockState);

    }

    @Override
    public int hashCode() {
        int result = Arrays.hashCode(faces);
        result = 31 * result + blockShape.hashCode();
        result = 31 * result + (obstacle ? 1 : 0);
        result = 31 * result + (transparent ? 1 : 0);
        result = 31 * result + blockState.hashCode();
        return result;
    }

    @Override
    public String toString() {
        return "BlockType(" +
                "faces=" + Arrays.toString(faces) +
                ", blockShape=" + blockShape +
                ", obstacle=" + obstacle +
                ", transparent=" + transparent +
                ", blockState=" + blockState +
                ')';
    }
}
